export enum UtilizadorFuncao {
  ADMIN = 'ADMIN',
  ARMAZEM = 'ARMAZEM',
  LABORATORIO = 'LABORATORIO',
  OPERADOR = 'OPERADOR',
  CONTROLO_QUALIDADE = 'CONTROLO_QUALIDADE',
  MANUTENCAO = 'MANUTENCAO',
  CADEIA_ABASTECIMENTO = 'CADEIA_ABASTECIMENTO',
  COMERCIAL = 'COMERCIAL',
  CONTABILIDADE = 'CONTABILIDADE',
  CLIENTE = 'CLIENTE',
}
