export enum ProcessoProducaoFaseEstado {
  PENDENTE = 'PENDENTE',
  PLANEADA = 'PLANEADA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  CONCLUIDA = 'CONCLUIDA',
  SALTADA = 'SALTADA',
  BLOQUEADA = 'BLOQUEADA',
}
