export enum ProcessoProducaoFaseEstado {
  PENDENTE = 'PENDENTE',
  PLANEADA = 'PLANEADA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  CONCLUIDA = 'CONCLUIDA',
  NAO_EXECUTADA = 'NAO_EXECUTADA',
  BLOQUEADA = 'BLOQUEADA',
}
