export enum SystemCodeContextType {
  PRODUCT_PLACE = 'PRODUCT_PLACE',
  PATH_IMPORT_FORMULA_LAB = 'PATH_IMPORT_FORMULA_LAB',
  CLIENT_PORTAL_LABORATORY_EMAIL = 'CLIENT_PORTAL_LABORATORY_EMAIL',
  CLIENT_PORTAL_ORDERS_EMAIL = 'CLIENT_PORTAL_ORDERS_EMAIL',
  CLIENT_PORTAL_QUALITY_CONTROL_EMAIL = 'CLIENT_PORTAL_QUALITY_CONTROL_EMAIL',
  CLIENT_PORTAL_ACCOUNTING_EMAIL = 'CLIENT_PORTAL_ACCOUNTING_EMAIL',
}
