export enum BusinessType {
  CLIENT = 'CLIENT',
  SUPPLIER = 'SUPPLIER',
  MANUFACTURER = 'MANUFACTURER',
  CONTRACTOR = 'CONTRACTOR',
}

export enum BusinessPaymentTerm {
  PROMPT_PAYMENT = 'PROMPT_PAYMENT',
  THIRTY_DAYS = 'THIRTY_DAYS',
  FORTY_FIVE_DAYS = 'FORTY_FIVE_DAYS',
  SIXTY_DAYS = 'SIXTY_DAYS',
  NINETY_DAYS = 'NINETY_DAYS',
}
