export enum FiberType {
  CO = 'CO',
  CO_ORG = 'CO_ORG',
  WS = 'WS',
  HA = 'HA',
  EL = 'EL',
  LI = 'LI',
  CLY = 'CLY',
  WO = 'WO',
  MD = 'MD',
  PA = 'PA',
  PES = 'PES',
  PES_REC = 'PES_REC',
  PES_CAT = 'PES_CAT',
  SE = 'SE',
  CV = 'CV',
  PAC = 'PAC',
}
