export enum OrderDeadlineStatusType {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  AWAITING_DEADLINE = 'AWAITING_DEADLINE',
  PROPOSED_BY_COMPANY = 'PROPOSED_BY_COMPANY',
  PROPOSED_BY_CLIENT = 'PROPOSED_BY_CLIENT',
}

export enum OrderDeadlineFormatType {
  DAY = 'DAY',
  WEEK = 'WEEK',
}

export enum OrderStatusType {
  IN_PRODUCTION = 'IN_PRODUCTION',
  DELIVERED = 'DELIVERED',
}
