export enum ProductType {
  AUXILIARY = 'AUXILIARY',
  COLORANT = 'COLORANT',
  FINISHING = 'FINISHING',
}

export enum ProductFormulaUnitType {
  CENTILITER_PER_LITER = 'CENTILITER_PER_LITER',
  GRAM_PER_LITER = 'GRAM_PER_LITER',
  GRAMS = 'GRAMS',
  KILOGRAM = 'KILOGRAM',
  LITER = 'LITER',
  MILLILITER = 'MILLILITER',
  PERCENTAGE = 'PERCENTAGE',
}

export enum ProductPurchaseUnitType {
  KILOGRAM = 'KILOGRAM',
  LITER = 'LITER',
}

export enum ProductIonsClassificationType {
  ANIONIC = 'ANIONIC',
  CATIONIC = 'CATIONIC',
  NON_IONIC = 'NON_IONIC',
  NOT_DEFINED = 'NOT_DEFINED',
}

export enum ProductDyeGroupType {
  ACID = 'ACID',
  CATIONIC = 'CATIONIC',
  CUBA = 'CUBA',
  DIRECT = 'DIRECT',
  DISPERSE = 'DISPERSE',
  NATURAL = 'NATURAL',
  OPTICAL = 'OPTICAL',
  PIGMENT = 'PIGMENT',
  REACTIVE = 'REACTIVE',
  SULFUROUS = 'SULFUROUS',
  BASIC = 'BASIC'
}

export enum ProductAuxiliaryType {
  ANTI_CREASE = 'ANTI_CREASE',
  ANTI_FELTING = 'ANTI_FELTING',
  ANTI_FOAM = 'ANTI_FOAM',
  ANTI_OIL = 'ANTI_OIL',
  ANTI_YELLOWING = 'ANTI_YELLOWING',
  NEUTRALIZER = 'NEUTRALIZER',
  STABILIZER = 'STABILIZER',
  BLEACHING = 'BLEACHING',
  DETERGENT = 'DETERGENT',
  DISPERSANT = 'DISPERSANT',
  EQUALIZER = 'EQUALIZER',
  ENZYME = 'ENZYME',
  PH_REGULATOR = 'PH_REGULATOR',
  SEQUESTRANT = 'SEQUESTRANT',
  WETTING_AGENT = 'WETTING_AGENT',
  ACID_GENERATOR = 'ACID_GENERATOR',
  CATALASE = 'CATALASE',
  FIXATIVE = 'FIXATIVE',
  RESIN = 'RESIN',
  SILICONE = 'SILICONE',
  SOFTENER = 'SOFTENER',
  OXIDIZING_AGENT = 'OXIDIZING_AGENT',
  REDUCING_AGENT = 'REDUCING_AGENT',
  SOAPING = 'SOAPING',
}

export enum ProductFinishingType {
  ANTI_BACTERIAL = 'ANTI_BACTERIAL',
  ANTI_PILLING = 'ANTI_PILLING',
  ANTI_STATIC = 'ANTI_STATIC',
  COOLING = 'COOLING',
  FLAME_RETARDANT = 'FLAME_RETARDANT',
  ODOR_CONTROL = 'ODOR_CONTROL',
  SOFTENER = 'SOFTENER',
  STAIN_RESISTANT = 'STAIN_RESISTANT',
  UV_PROTECTION = 'UV_PROTECTION',
  WATER_ABSORBENT = 'WATER_ABSORBENT',
  WATER_REPELLENT = 'WATER_REPELLENT',
  WRINKLE_RESISTANT = 'WRINKLE_RESISTANT',
  OIL_REPELLENT = 'OIL_REPELLENT',
  COATING = 'COATING',
  NEEDLE_PUNCHED = 'NEEDLE_PUNCHED',
  THERMOFIXATIVE = 'THERMOFIXATIVE',
  AROMA = 'AROMA',
  SILICONE_SOFTENER = 'SILICONE_SOFTENER',
  NON_SILICONE_SOFTENER = 'NON_SILICONE_SOFTENER',
  EDGE_RESIN = 'EDGE_RESIN',
  FINISHING_RESIN = 'FINISHING_RESIN',
}

export const ProductSubType = {
  ...ProductDyeGroupType,
  ...ProductAuxiliaryType,
  ...ProductFinishingType,
} as const;

export type ProductSubType =
  (typeof ProductSubType)[keyof typeof ProductSubType];
