export enum UserRoleType {
  ADMIN = 'ADMIN',
  WAREHOUSE = 'WAREHOUSE',
  LABORATORY = 'LABORATORY',
  PLANNING = 'PLANNING',
  OPERATOR = 'OPERATOR',
  QUALITY_CONTROL = 'QUALITY_CONTROL',
  MAINTENANCE = 'MAINTENANCE',
  SUPPLY_CHAIN = 'SUPPLY_CHAIN',
  FRONTDESK = 'FRONTDESK',
  BACKOFFICE = 'BACKOFFICE',
  SALES = 'SALES',
  ITSUPPORT = 'ITSUPPORT',
  ACCOUNTING = 'ACCOUNTING',
  CLIENT = 'CLIENT',
}

export enum UserOriginType {
  DYEING_HOUSE = 'DYEING_HOUSE',
  CLIENT = 'CLIENT',
}
