export enum Certificacao {
  GOTS_7 = 'GOTS_7',
  GRS = 'GRS',
  OCS = 'OCS',
  OEKOTEX_1 = 'OEKOTEX_1',
  OEKOTEX_2 = 'OEKOTEX_2',
  RCS = 'RCS',
  REACH = 'REACH',
  STEP = 'STEP',
  THE_LIST_A = 'THE_LIST_A',
  THE_LIST_C = 'THE_LIST_C',
  ZDHC_1 = 'ZDHC_1',
  ZDHC_2 = 'ZDHC_2',
  ZDHC_3 = 'ZDHC_3',
}
