export enum ProdutoTipo {
  AUXILIAR = 'AUXILIAR',
  CORANTE = 'CORANTE',
  ACABAMENTO = 'ACABAMENTO',
  BASE = 'BASE',
}

export enum ProdutoReceitaLaboratorioUnidade {
  CENTILITRO_POR_LITRO = 'CENTILITRO_POR_LITRO',
  GRAMA_POR_LITRO = 'GRAMA_POR_LITRO',
  PERCENTAGEM = 'PERCENTAGEM',
}

export enum ProdutoReceitaTinturariaUnidade {
  GRAMAS = 'GRAMAS',
  QUILOGRAMA = 'QUILOGRAMA',
  LITRO = 'LITRO',
  MILILITRO = 'MILILITRO',
}

export enum ProdutoClassificacaoIonica {
  ANIONICA = 'ANIONICA',
  CATIONICA = 'CATIONICA',
  NAO_IONICA = 'NAO_IONICA',
  NAO_DEFINIDA = 'NAO_DEFINIDA',
}

export enum GrupoCorantes {
  ACIDO = 'ACIDO',
  CATIONICO = 'CATIONICO',
  CUBA = 'CUBA',
  DIRETO = 'DIRETO',
  DISPERSO = 'DISPERSO',
  NATURAL = 'NATURAL',
  OTICO = 'OTICO',
  PIGMENTO = 'PIGMENTO',
  REATIVO = 'REATIVO',
  SULFUROSO = 'SULFUROSO',
  BASICO = 'BASICO',
}

export enum ProdutoAuxiliarTipo {
  ANTI_VINCO = 'ANTI_VINCO',
  ANTI_FELTRAGEM = 'ANTI_FELTRAGEM',
  ANTI_ESPUMA = 'ANTI_ESPUMA',
  ANTI_OLEO = 'ANTI_OLEO',
  ANTI_AMARELECIMENTO = 'ANTI_AMARELECIMENTO',
  NEUTRALIZADOR = 'NEUTRALIZADOR',
  ESTABILIZADOR = 'ESTABILIZADOR',
  BRANQUEAMENTO = 'BRANQUEAMENTO',
  DETERGENTE = 'DETERGENTE',
  DISPERSANTE = 'DISPERSANTE',
  IGUALIZADOR = 'IGUALIZAOR',
  ENZIMA = 'ENZIMA',
  REGULADOR_PH = 'REGULADOR_PH',
  SEQUESTRANTE = 'SEQUESTRANTE',
  MOLHANTE = 'MOLHANTE',
  GERADOR_ACIDO = 'GERADOR_ACIDO',
  CATALASE = 'CATALASE',
  FIXADOR = 'FIXADOR',
  RESINA = 'RESINA',
  SILICONE = 'SILICONE',
  AMACIADOR = 'AMACIADOR',
  AGENTE_OXIDANTE = 'AGENTE_OXIDANTE',
  AGENTE_REDUTOR = 'AGENTE_REDUTOR',
  SABAO = 'SABAO',
}

export enum ProdutoAcabamentoTipo {
  ANTI_BACTERIANO = 'ANTI_BACTERIANO',
  ANTI_PILLING = 'ANTI_PILLING',
  ANTI_ESTATICO = 'ANTI_ESTATICO',
  TERMOREGULADOR = 'TERMOREGULADOR',
  RETARDADOR_CHAMA = 'RETARDADOR_CHAMA',
  CONTROLO_ODOR = 'CONTROLO_ODOR',
  AMACIADOR = 'AMACIADOR',
  ANTI_MANCHA = 'ANTI_MANCHA',
  PROTECAO_UV = 'PROTECAO_UV',
  ABSORVENTE_AGUA = 'ABSORVENTE_AGUA',
  REPELENTE_AGUA = 'REPELENTE_AGUA',
  ANTI_VINCOS = 'ANTI_VINCOS',
  REPELENTE_OLEO = 'REPELENTE_OLEO',
  PICAR_AGULHA = 'PICAR_AGULHA',
  TERMOFIXADOR = 'TERMOFIXADOR',
  AROMA = 'AROMA',
  AMACIADOR_SILICONE = 'AMACIADOR_SILICONE',
  AMACIADOR_NAO_SILICONE = 'AMACIADOR_NAO_SILICONE',
  RESINA_OURELA = 'RESINA_OURELA',
}

export const ProdutoSubTipo = {
  ...GrupoCorantes,
  ...ProdutoAuxiliarTipo,
  ...ProdutoAcabamentoTipo,
} as const;

export type ProdutoSubTipo = (typeof ProdutoSubTipo)[keyof typeof ProdutoSubTipo];
