export enum OrganizacaoConfigContexto {
  PATH_IMPORT_FORMULA_LAB = 'PATH_IMPORT_FORMULA_LAB',
  EMAIL_LABORATORIO = 'EMAIL_LABORATORIO',
  ENCOMENDA_ORDER_NUMBER_COUNTER = 'ENCOMENDA_ORDER_NUMBER_COUNTER',
}
