export enum OrganizacaoConfigContexto {
  PATH_IMPORT_FORMULA_LAB = 'PATH_IMPORT_FORMULA_LAB',
  EMAIL_LABORATORIO = 'EMAIL_LABORATORIO',
  ENCOMENDA_ORDEM_SERVICO_COUNTER = 'ENCOMENDA_ORDEM_SERVICO_COUNTER',
  DATA_ENTREGA_ENCOMENDA_PREVISTA_DIAS = 'DATA_ENTREGA_ENCOMENDA_PREVISTA_DIAS',
}
