export enum EncomendaArtigoDefeitoTipo {
  BURACO = 'BURACO',
  FALHA_MALHA = 'FALHA_MALHA',
  FIO_PUXADO = 'FIO_PUXADO',
  NO = 'NO',
  BARRADO = 'BARRADO',
  MANCHA = 'MANCHA',
  DIFERENCA_COR = 'DIFERENCA_COR',
  CONTAMINACAO = 'CONTAMINACAO',
  RUGA_VINCO = 'RUGA_VINCO',
  PILLING = 'PILLING',
  OUTRO = 'OUTRO',
}
