export enum EncomendaEstado {
  INICIADA = 'INICIADA',
  EM_PRODUCAO = 'EM_PRODUCAO',
  PRONTA_PARA_ENTREGA = 'PRONTA_PARA_ENTREGA',
  PARCIALMENTE_ENTREGUE = 'PARCIALMENTE_ENTREGUE', // Pelo menos um artigo entregue, mas não todos
  ENTREGUE = 'ENTREGUE', // Todos os artigos entregues
  CANCELADA = 'CANCELADA',
}

export enum EncomendaArtigoFaseEstado {
  AGUARDA_PLANEAMENTO = 'AGUARDA_PLANEAMENTO',
  PLANEADA = 'PLANEADA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
  BLOQUEADA = 'BLOQUEADA',
}

export enum EncomendaArtigoPartidaMotivo {
  GESTAO_PLANEAMENTO = 'GESTAO_PLANEAMENTO',
  NAO_CONFORMIDADE_PRODUCAO = 'NAO_CONFORMIDADE_PRODUCAO',
}

export enum EncomendaDevolucaoMotivo {
  TOM_COR_DIFERENTE = 'TOM_COR_DIFERENTE',
  GRAMAGEM_FORA_ESPECIFICACAO = 'GRAMAGEM_FORA_ESPECIFICACAO',
  LARGURA_FORA_ESPECIFICACAO = 'LARGURA_FORA_ESPECIFICACAO',
  ENCOLHIMENTO_FORA_ESPECIFICACAO = 'ENCOLHIMENTO_FORA_ESPECIFICACAO',
  MANCHA_CONTAMINACAO = 'MANCHA_CONTAMINACAO',
  SOLIDEZ_FORA_ESPECIFICACAO = 'SOLIDEZ_FORA_ESPECIFICACAO',
}
