export enum PedidoCorEstado {
  EM_PROGRESSO = 'EM_PROGRESSO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  CONCLUIDO = 'CONCLUIDO',
}

export enum EnsaioEstado {
  INICIADO = 'INICIADO',
  ENVIADO = 'ENVIADO',
  DESCARTADO = 'DESCARTADO',
  REJEITADO = 'REJEITADO',
  APROVADO = 'APROVADO',
}
