export enum WorkOrderDeadlineStatusType {
  APPROVED = 'APPROVED',
  AUTO_APPROVED = 'AUTO_APPROVED',
  REJECTED = 'REJECTED',
  PROPOSED_BY_COMPANY = 'PROPOSED_BY_COMPANY',
  PROPOSED_BY_CLIENT = 'PROPOSED_BY_CLIENT',
}

export enum WorkOrderDeadlineFormatType {
  DAY = 'DAY',
  WEEK = 'WEEK',
}

export enum WorkOrderStatusType {
  AWAITING_LAB_DIP = 'AWAITING_LAB_DIP',
  AWAITING_PREPARATION = 'AWAITING_PREPARATION',
  IN_PRODUCTION = 'IN_PRODUCTION',
  IN_QUALITY_CONTROL = 'IN_QUALITY_CONTROL',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}
