export enum AppModules {
  ACCOUNTING = 'accounting',
  AUTH = 'auth',
  BUSINESS_ENTITIES = 'business-entities',
  CHEMICALS = 'chemicals',
  CLIENT_MANAGEMENT = 'client-management',
  CLIENT_PORTAL = 'client-portal',
  COLOR_CATALOG = 'color-catalog',
  DASHBOARDS = 'dashboards',
  FABRIC_CATALOG = 'fabric-catalog',
  LABORATORY = 'laboratory',
  MAINTENANCE = 'maintenance',
  MACHINES = 'machines',
  ORDERS = 'orders',
  PRODUCTION = 'production',
  QUALITY_CONTROL = 'quality-control',
  RECIPES = 'recipes',
  USERS = 'users',
  WAREHOUSE = 'warehouse',
  PRICING = 'pricing',
}
