export enum FormMessageType {
  REQUIRED = 'required',
  POSITIVE = 'positive',
  MIN_CHARACTERS = 'mincharacters',
  MAX_CHARACTERS = 'maxcharacters',
  MAX_EXCEEDED = 'maxexceeded',
  PANTONE_REGEX = 'pantoneregex',
  EMAIL = 'email',
  INTEGER = 'integer',
  ENUM = 'enum',
  WHITE_SPACE = 'whitespace',
  NO_MATCH_PASSWORD = 'nomatchpassword',
  INVALID_PERCENTAGE = 'invalidpercentage',
  MISSING_DOC_DATE = 'missingdocdate',
  MISSING_DOC = 'missingdoc',
  ONLY_FUTURE_DATE = 'onlyfuturedate',
  DUPLICATES = 'duplicates',
}
